#SPDX-License-Identifier: MIT-0
---
# tasks file
#
- name: Harden SSH configuration
  include_tasks: harden_ssh.yml

- name: Update apt cache and upgrade packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist

- name: Configure firewall with UFW
  include_tasks: configure_ufw.yml

- name: Install tailscale
  include_tasks: install_tailscale.yml

- name: Install Docker
  include_tasks: install_docker.yml

- name: Install Neovim
  include_tasks: install_nvim.yml

- name: Install cloudflared
  include_tasks: install_cloudflared.yml

- name: Install kubectl
  include_tasks: install_kubectl.yml
