- name: Stop docker service if running
  listen: setup docker rootless
  ansible.builtin.service:
    name: docker.service
    state: stopped
    enabled: no

- name: Stop docker socket if running
  listen: setup docker rootless
  ansible.builtin.service:
    name: docker.socket
    state: stopped
    enabled: no
- name: Delete docker socket
  listen: setup docker rootless
  ansible.builtin.file:
    name: /var/run/docker.sock
    state: absent

- name: Add current user to docker group
  listen: setup docker rootless
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Execute docker rootless setup script
  listen: setup docker rootless
  become: false
  ansible.builtin.command: "dockerd-rootless-setuptool.sh install"

